INSERT INTO category (description) VALUES ('South Indian');
INSERT INTO category (description) VALUES ('Punjabi');
INSERT INTO category (description) VALUES ('Bihari');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pinch');
INSERT INTO unit_of_measure (description) VALUES ('Milligram');
INSERT INTO unit_of_measure (description) VALUES ('Gram');
INSERT INTO unit_of_measure (description) VALUES ('Kilogram');
INSERT INTO unit_of_measure (description) VALUES ('Small');
INSERT INTO unit_of_measure (description) VALUES ('Big');